### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by pirupius** [street-lights/data-collection-tool#11]
For the start, only one language will be available but we want to open it up for all possible languages. 

**Tasks:** 

- [ ] Users should be able to select their language of choice so that the lessons are tailored to that specific language. 

- [ ] Store user progress for each language so that they can continue from where they stopped. 

- [ ] Tutors should be able to add content based on the various languages.
