### ISSUE TITLE
User Profile and Settings

### ISSUE THREAD

**Issue by pirupius** [street-lights/data-collection-tool#9]
**Tasks:**

- [x] Users should be able to view their profile information and edit their customer data

- [ ] Users should be able to change passwords and forgot password should be configured so that those that have lost their passwords can change them. 

- [ ] Users should be able to upload their profile photo so that other users can easily identify them and also create a sense of security on who their interacting with.

**Comment by pirupius** [comment]
last 2 tasks being worked on here :point_right: #18
